FILE(GLOB CORE_HEADERS core/*.hpp)
FILE(GLOB CORE_SOURCES core/*.cpp)
FILE(GLOB CORE_IO_HEADERS core/io/*.hpp)
FILE(GLOB CORE_IO_SOURCES core/io/*.cpp)
	
set(${NAME}_CORE_HEADERS ${CORE_HEADERS} ${CORE_IO_HEADERS})
set(${NAME}_CORE_SOURCES ${CORE_SOURCES} ${CORE_IO_SOURCES})
